### ISSUE TITLE
getting the 'missing token and charge amount' error with default options

### ISSUE THREAD

**Issue by tensiuyan** [openerror/skygearStripeDemo#1]
I placed an order with the default **desired product** and default **order amount**, however getting the 'missing token and charge amount' error.

![screen shot 2018-04-16 at 12 50 25 pm](https://user-images.githubusercontent.com/16287874/38790603-f2298a82-4174-11e8-9cf4-c2e1929aaec3.png)

**Comment by openerror** [comment]
HTML form now reminds users to choose an amount. Also, a JS alert would be triggered after clicking Submit, if the user still ends up not choosing any value.

**Comment by tensiuyan** [comment]
Cool! it works now.
