### ISSUE TITLE
Payment function broken

### ISSUE THREAD

**Issue by openerror** [openerror/skygearStripeDemo#10]
Everything was working fine yesterday, but today I saw the following error in JS console. Any ideas?

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://babystep.skygeario.com/submitPayment. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

*submitPayment* is the name of the cloud function, fyi.

**Comment by david90** [comment]
Hi Everest,

It's my wrong when regrouping the js code, please help update api endpoint from`https://babystep.skygeario.com/`  to `https://babysteps.skygeario.com/` at https://github.com/openerror/skygearStripeDemo/blob/master/public_html/index.js#L2

**Comment by openerror** [comment]
Got it. Thanks for debugging!
