### ISSUE TITLE
Supply test card information above the 'submit payment' button

### ISSUE THREAD

**Issue by tensiuyan** [openerror/skygearStripeDemo#2]
Frustrated the first time what to input in the credit/debit card field, because I don't want to use my real credit card. Later found out the use of test cards: https://stripe.com/docs/testing

Shall we simply supply the test card information right above the submit payment button as  a note or have them the default value of the payment input form?

The test card information I use:

VISA: 4242 4242 4242 4242
Expiry date: 11/29
CSV: 222
Postal code: 36310

**Comment by openerror** [comment]
Resolved by adding explanations in both README.md and the HTML interface
