### ISSUE TITLE
Not getting the order confirmation email

### ISSUE THREAD

**Issue by tensiuyan** [openerror/skygearStripeDemo#3]
I am not getting the order confirmation email. My email is caroltang8292@gmail.com

**Comment by openerror** [comment]
I have actually tried to send an email to myself, using Skymail + Gmail. Google then sent me a warning email, saying that the request is not secure. There's a workaround, but I would have to lower security settings for my Google account. Not ideal.

<img width="786" alt="screen shot 2018-04-25 at 10 25 37" src="https://user-images.githubusercontent.com/11012723/39262007-06e88ae0-4873-11e8-8b75-0049aa4883d2.png">

**Comment by tensiuyan** [comment]
Thanks for the investigate. If that's the case, prefer removing the email sending feature. Thanks!

**Comment by openerror** [comment]
Agreed. Since David's edits have already removed the email input form, I'm closing the issue.
