### ISSUE TITLE
Also save the name of the buyer in the database

### ISSUE THREAD

**Issue by tensiuyan** [openerror/skygearStripeDemo#4]
Also the name of the buyer in the database, so that users can know more easily if his order has successfully been saved in the database.

**Comment by tensiuyan** [comment]
Thanks! I was able to see my name in the database. However I am also able to save the record without entering my name. 

![screen shot 2018-04-27 at 5 12 37 pm](https://user-images.githubusercontent.com/16287874/39354956-6d7cb174-4a3e-11e8-8915-ed1829348b00.png)

Can you help check the validation? Thanks!

**Comment by openerror** [comment]
I forgot to run *skycli deploy* after pushing to github. Try again --- it should work now.

**Comment by tensiuyan** [comment]
Thanks it works now. Closing this issue.
